import { useMemo,useState } from 'react'
import { Check, Search, ShoppingCart, SlidersHorizontal, X } from 'lucide-react'
import { Navigate, Link } from 'react-router-dom'
import { useAppData } from '../context/AppDataContext'
import { money } from '../utils/commerce'

export default function StorePage(){
  const {data,loading,addToCart,cart}=useAppData(); const [query,setQuery]=useState(''); const [category,setCategory]=useState('Todos'); const [subcategory,setSubcategory]=useState('Todos'); const [brand,setBrand]=useState('Todas'); const [mobileFilters,setMobileFilters]=useState(false); const [added,setAdded]=useState(null)
  const subcategories=useMemo(()=>{if(!data)return[]; if(category==='Todos')return[...new Set(data.productCategories.flatMap(x=>x.active?x.subcategories.filter(s=>s.active).map(s=>s.name):[]))]; return data.productCategories.find(x=>x.name===category)?.subcategories.filter(x=>x.active).map(x=>x.name)||[]},[data,category])
  const filtered=useMemo(()=>data?data.products.filter(x=>x.active).filter(x=>data.brands.some(b=>b.active&&b.name===x.brand)).filter(x=>category==='Todos'||x.category===category).filter(x=>subcategory==='Todos'||x.subcategory===subcategory).filter(x=>brand==='Todas'||x.brand===brand).filter(x=>!query.trim()||`${x.name} ${x.brand} ${x.category} ${x.subcategory} ${x.sku}`.toLowerCase().includes(query.toLowerCase())):[],[data,query,category,subcategory,brand])
  if(loading)return <div className="screen-loader">Cargando store…</div>; if(!data.settings.storeEnabled)return <Navigate to="/" replace/>
  const clear=()=>{setQuery('');setCategory('Todos');setSubcategory('Todos');setBrand('Todas')}
  const add=product=>{addToCart(product.id);setAdded(product.id);setTimeout(()=>setAdded(null),1100)}
  return <section className="page-section surface-section"><div className="container"><div className="page-hero"><span className="section-kicker">AutoSpa #33 Store</span><h1>Productos profesionales para detailing y mantenimiento</h1><p>Armá tu pedido online. No se cobra desde la web: enviás el detalle por WhatsApp y el negocio confirma disponibilidad y total final.</p></div>
    <div className="store-layout"><aside className={`store-sidebar ${mobileFilters?'show-mobile':''}`}><div className="filter-heading"><strong>Filtros</strong><button onClick={clear}><X size={15}/> Limpiar</button></div><label><span>Categoría</span><select value={category} onChange={e=>{setCategory(e.target.value);setSubcategory('Todos')}}><option>Todos</option>{data.productCategories.filter(x=>x.active).map(x=><option key={x.id}>{x.name}</option>)}</select></label><label><span>Subcategoría</span><select value={subcategory} onChange={e=>setSubcategory(e.target.value)}><option>Todos</option>{subcategories.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Marca</span><select value={brand} onChange={e=>setBrand(e.target.value)}><option>Todas</option>{data.brands.filter(x=>x.active).map(x=><option key={x.id}>{x.name}</option>)}</select></label></aside>
      <div><div className="store-search-row"><label className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto, marca o SKU..."/></label><button className="btn btn-secondary mobile-filter-button" onClick={()=>setMobileFilters(x=>!x)}><SlidersHorizontal size={18}/> Filtros</button></div><div className="results-row"><strong>{filtered.length} productos</strong><Link className="text-link" to="/carrito"><ShoppingCart size={16}/> Ver carrito ({cart.reduce((s,x)=>s+x.quantity,0)})</Link></div>
      <div className="products-grid">{filtered.map(product=><article className="product-card" key={product.id}><Link className="product-card-link" to={`/store/producto/${product.id}`} aria-label={`Ver ${product.name}`}><div className="product-image"><img src={product.image} alt={product.name}/><span className="brand-badge">{product.brand}</span>{product.featured&&<span className="featured-badge">Destacado</span>}</div></Link><div className="product-body"><small className="product-taxonomy">{product.category} · {product.subcategory}</small><Link className="product-title-link" to={`/store/producto/${product.id}`}><h2>{product.name}</h2></Link><div className="product-meta"><span>{product.size}</span><span className={product.stock<=product.minStock?'stock-low':''}>{product.stock>0?`Stock: ${product.stock}`:'Sin stock'}</span></div><Link className="product-details-link" to={`/store/producto/${product.id}`}>Ver detalle</Link><div className="product-footer"><strong>{data.settings.showPrices?money(product.price):'Consultar'}</strong><button disabled={product.stock<=0} onClick={()=>add(product)}>{added===product.id?<><Check size={18}/> Agregado</>:<><ShoppingCart size={18}/> Agregar</>}</button></div></div></article>)}</div></div></div>
  </div></section>
}
