import { useRef,useState } from 'react'
import { Download,FileDown,FileSpreadsheet,Upload } from 'lucide-react'
import { apiRepository,adminCodeStorage } from '../repositories/apiRepository'
const API_URL=(import.meta.env.VITE_API_URL||'https://localhost:7208').replace(/\/$/,'')
const options=[['sku','SKU'],['name','Nombre'],['brand','Marca'],['category','Categoría'],['subcategory','Subcategoría'],['cost','Costo'],['price','Precio'],['size','Presentación'],['stock','Stock'],['minStock','Stock mínimo'],['active','Estado']]
export default function ProductDataTools({onImported}){
 const input=useRef();const[selected,setSelected]=useState(['name','cost','price','size','stock']);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('')
 const toggle=k=>setSelected(v=>v.includes(k)?v.filter(x=>x!==k):[...v,k])
 const download=async(type,path)=>{setErr('');try{const r=await fetch(`${API_URL}${path}`,{headers:{'X-Admin-Code':adminCodeStorage.get(),'ngrok-skip-browser-warning':'true'}});if(!r.ok)throw new Error('No se pudo generar el archivo.');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=type;a.click();URL.revokeObjectURL(a.href)}catch(e){setErr(e.message)}}
 const importFile=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setErr('');setMsg('');try{const r=await apiRepository.importProductsExcel(file);setMsg(`${r.message} Ajustes de stock: ${r.stockAdjusted}. ${r.errors?.length?`Filas con observaciones: ${r.errors.length}.`:''}`);await onImported?.()}catch(e){setErr(e.message)}finally{setBusy(false);e.target.value=''}}
 const fields=selected.join(',')
 return <section className="admin-panel data-tools"><div className="panel-title-row"><div><h2>Importar / exportar productos</h2><p>Importá un Excel o generá una planilla de stock con únicamente las columnas que necesites.</p></div><FileSpreadsheet size={22}/></div>{msg&&<div className="notice-success">{msg}</div>}{err&&<div className="notice-error">{err}</div>}<div className="data-tools-actions"><button className="btn btn-secondary" onClick={()=>download('AutoSpa33-Plantilla-Productos.xlsx','/api/admin/product-files/template')}><Download size={16}/> Plantilla Excel</button><button className="btn btn-secondary" onClick={()=>input.current?.click()} disabled={busy}><Upload size={16}/> {busy?'Importando…':'Importar Excel'}</button><input ref={input} hidden type="file" accept=".xlsx" onChange={importFile}/></div><div className="export-fields">{options.map(([k,label])=><label key={k}><input type="checkbox" checked={selected.includes(k)} onChange={()=>toggle(k)}/><span>{label}</span></label>)}</div><div className="data-tools-actions"><button className="btn btn-primary" disabled={!selected.length} onClick={()=>download('AutoSpa33-Stock.xlsx',`/api/admin/product-files/export/excel?fields=${encodeURIComponent(fields)}`)}><FileSpreadsheet size={16}/> Exportar Excel</button><button className="btn btn-secondary" disabled={!selected.length} onClick={()=>download('AutoSpa33-Stock.pdf',`/api/admin/product-files/export/pdf?fields=${encodeURIComponent(fields)}`)}><FileDown size={16}/> Exportar PDF</button></div><small className="field-help">La importación identifica productos por SKU. Si el SKU ya existe, actualiza sus datos; si cambia Stock, registra un movimiento de ajuste para conservar trazabilidad.</small></section>
}
