import { useEffect, useState } from 'react'
import { CheckCircle2, Edit3, MessageCircle, Minus, Plus, RefreshCw, Trash2, XCircle } from 'lucide-react'
import { useAppData } from '../../context/AppDataContext'
import { money,dateTime } from '../../utils/commerce'
import { buildWhatsappUrl } from '../../utils/whatsapp'

const orderMessage = order => `Hola ${order.customerName}, te confirmamos tu pedido ${order.publicCode} en AutoSpa #33.\n\nTotal confirmado: ${money(order.total)}\n\nTu pedido ya fue revisado y confirmado. ¡Gracias!`

export default function AdminOrdersPage(){
 const {data,loading,updateOrder,confirmSale,refreshOrders}=useAppData(); const [editing,setEditing]=useState(null); const [items,setItems]=useState([]); const [message,setMessage]=useState(''); const [modalError,setModalError]=useState(''); const [payment,setPayment]=useState('Transferencia'); const [addProductId,setAddProductId]=useState('')
 useEffect(()=>{const reload=()=>refreshOrders().catch(()=>{});reload();window.addEventListener('focus',reload);return()=>window.removeEventListener('focus',reload)},[])
 if(loading||!data)return <div className="screen-loader">Cargando…</div>
 const pending=(data.orders||[]).filter(x=>x.status==='pending'); const closed=(data.orders||[]).filter(x=>x.status!=='pending')
 const open=order=>{setEditing(order);setItems(order.items.map(x=>({...x})));setModalError('');setAddProductId('')}; const total=items.reduce((s,x)=>s+Number(x.quantity)*Number(x.unitPrice),0)
 const updateQty=(id,q)=>setItems(v=>q<=0?v.filter(x=>x.productId!==id):v.map(x=>x.productId===id?{...x,quantity:q,subtotal:q*x.unitPrice}:x)); const updatePrice=(id,price)=>setItems(v=>v.map(x=>x.productId===id?{...x,unitPrice:Number(price)||0,subtotal:x.quantity*(Number(price)||0)}:x))
 const addProduct=()=>{const p=data.products.find(x=>x.id===Number(addProductId));if(!p)return;setItems(v=>{const found=v.find(x=>x.productId===p.id);return found?v.map(x=>x.productId===p.id?{...x,quantity:x.quantity+1,subtotal:(x.quantity+1)*x.unitPrice}:x):[...v,{productId:p.id,sku:p.sku,name:p.name,quantity:1,unitPrice:p.price,subtotal:p.price}]});setAddProductId('')}
 const confirm=async()=>{const original=editing;const result=await confirmSale({source:'web_order',orderId:editing.id,customerName:editing.customerName,phone:editing.phone,paymentMethod:payment,notes:editing.notes,items});if(!result.ok){setModalError(result.error);return}setEditing(null);setMessage(`Pedido ${original.publicCode} confirmado como venta ${result.sale.number}. Stock descontado.`)}
 const sendWhatsapp=order=>{const url=buildWhatsappUrl(order.phone,orderMessage(order));if(url)window.open(url,'_blank','noopener,noreferrer')}
 return <><div className="admin-page-header"><div><span className="section-kicker">Pedidos online</span><h1>Solicitudes de productos</h1><p>La solicitud queda pendiente sin descontar stock. Revisala y confirmala para generar la venta; después podés avisar al cliente por WhatsApp.</p></div><button className="btn btn-secondary" onClick={()=>refreshOrders()}><RefreshCw size={17}/> Actualizar</button></div>{message&&<div className="notice-success">{message}</div>}
 <div className="order-admin-stats"><article><strong>{pending.length}</strong><span>Pendientes</span></article><article><strong>{closed.filter(x=>x.status==='confirmed').length}</strong><span>Confirmados</span></article><article><strong>{closed.filter(x=>x.status==='cancelled').length}</strong><span>Cancelados</span></article></div>
 <div className="orders-grid">{pending.length===0&&<div className="admin-panel empty-agenda full-span">No hay pedidos pendientes.</div>}{pending.map(order=><article className="admin-panel order-request" key={order.id}><div className="order-request-head"><div><span className="status pending">Pendiente</span><h2>{order.publicCode}</h2><p>{order.customerName} · {order.phone}</p></div></div><div className="order-mini-lines">{order.items.map(x=><span key={x.productId}>{x.quantity} × {x.name}</span>)}</div><div className="order-request-total"><span>{dateTime(order.createdAt)}</span><strong>{money(order.total)}</strong></div><div className="request-actions"><button className="btn btn-primary" onClick={()=>open(order)}><Edit3 size={16}/> Revisar y confirmar</button><button className="btn btn-secondary" onClick={()=>updateOrder(order.id,{status:'cancelled'})}><XCircle size={16}/> Cancelar</button></div></article>)}</div>
 {closed.length>0&&<div className="admin-panel sales-history"><h2>Historial de pedidos</h2><div className="history-list">{closed.slice(0,20).map(x=><article key={x.id}><div><strong>{x.publicCode}</strong><span>{x.customerName}</span><small>{dateTime(x.createdAt)}</small></div><div className="request-actions"><span className={`status ${x.status}`}>{x.status==='confirmed'?'Confirmado':'Cancelado'}</span>{x.status==='confirmed'&&x.phone&&<button className="btn btn-secondary" onClick={()=>sendWhatsapp(x)}><MessageCircle size={15}/> WhatsApp</button>}</div></article>)}</div></div>}
 {editing&&<div className="modal-backdrop"><div className="modal modal-wide"><button className="modal-close" onClick={()=>setEditing(null)}>×</button><span className="section-kicker">Revisión de pedido</span><h2>{editing.publicCode}</h2><p className="modal-subtitle">{editing.customerName} · {editing.phone}. Compará contra stock físico antes de confirmar.</p><div className="order-edit-lines">{items.map(row=>{const p=data.products.find(x=>x.id===row.productId);return <article key={row.productId}><div><strong>{row.name}</strong><small>Stock actual: {p?.stock??0}</small><input className="inline-price-input" type="number" min="0" value={row.unitPrice} onChange={e=>updatePrice(row.productId,e.target.value)}/></div><div className="qty-control"><button onClick={()=>updateQty(row.productId,row.quantity-1)}><Minus size={14}/></button><strong>{row.quantity}</strong><button onClick={()=>updateQty(row.productId,row.quantity+1)}><Plus size={14}/></button></div><strong>{money(row.quantity*row.unitPrice)}</strong><button className="danger-icon" onClick={()=>updateQty(row.productId,0)}><Trash2 size={15}/></button></article>})}</div><div className="order-add-product"><select value={addProductId} onChange={e=>setAddProductId(e.target.value)}><option value="">Agregar otro producto…</option>{data.products.filter(x=>x.active).map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name} · stock {p.stock}</option>)}</select><button className="btn btn-secondary" onClick={addProduct} disabled={!addProductId}><Plus size={16}/> Agregar</button></div>{modalError&&<div className="notice-error">{modalError}</div>}<label><span>Medio de pago</span><select value={payment} onChange={e=>setPayment(e.target.value)}><option>Transferencia</option><option>Efectivo</option><option>Mercado Pago</option><option>Tarjeta</option><option>Otro</option></select></label><div className="pos-total"><span>Total final</span><strong>{money(total)}</strong></div><button className="btn btn-primary full-width" disabled={!items.length} onClick={confirm}><CheckCircle2 size={17}/> Confirmar pedido y registrar venta</button></div></div>}
 </>
}
