import { useEffect, useState } from 'react'
import { CheckCircle2, Edit3, MessageCircle, Minus, Plus, RefreshCw, ShoppingBag, Trash2, XCircle } from 'lucide-react'
import { useAppData } from '../../context/AppDataContext'
import { money,dateTime } from '../../utils/commerce'
import { buildWhatsappUrl } from '../../utils/whatsapp'

const orderMessage=order=>`Hola ${order.customerName}, te confirmamos tu pedido ${order.publicCode} en AutoSpa #33.\n\nTotal confirmado: ${money(order.total)}\nMedio de pago elegido: ${order.paymentMethod}.\n\nEl pedido está confirmado. Una vez realizado/verificado el pago coordinamos la entrega o retiro. ¡Gracias!`
const statusLabel=status=>({pending:'Pendiente',confirmed:'Confirmado',closed:'Venta cerrada',cancelled:'Cancelado'}[status]||status)

export default function AdminOrdersPage(){
 const {data,loading,updateOrder,confirmOrder,closeOrder,refreshOrders}=useAppData()
 const [editing,setEditing]=useState(null);const [items,setItems]=useState([]);const [message,setMessage]=useState('');const [modalError,setModalError]=useState('');const [addProductId,setAddProductId]=useState('');const [closingId,setClosingId]=useState(null)
 useEffect(()=>{const reload=()=>refreshOrders().catch(()=>{});reload();window.addEventListener('focus',reload);return()=>window.removeEventListener('focus',reload)},[])
 if(loading||!data)return <div className="screen-loader">Cargando…</div>
 const orders=Array.isArray(data.orders)?data.orders:(data.orders?.items||[])
 const pending=orders.filter(x=>x.status==='pending'),confirmed=orders.filter(x=>x.status==='confirmed'),history=orders.filter(x=>x.status==='closed'||x.status==='cancelled')
 const open=order=>{setEditing(order);setItems((order.items||[]).map(x=>({...x})));setModalError('');setAddProductId('')}
 const total=items.reduce((s,x)=>s+Number(x.quantity)*Number(x.unitPrice),0)
 const updateQty=(id,q)=>setItems(v=>q<=0?v.filter(x=>x.productId!==id):v.map(x=>x.productId===id?{...x,quantity:q,subtotal:q*x.unitPrice}:x))
 const updatePrice=(id,price)=>setItems(v=>v.map(x=>x.productId===id?{...x,unitPrice:Number(price)||0,subtotal:x.quantity*(Number(price)||0)}:x))
 const addProduct=()=>{const p=data.products.find(x=>x.id===Number(addProductId));if(!p)return;setItems(v=>{const found=v.find(x=>x.productId===p.id);return found?v.map(x=>x.productId===p.id?{...x,quantity:x.quantity+1,subtotal:(x.quantity+1)*x.unitPrice}:x):[...v,{productId:p.id,sku:p.sku,name:p.name,quantity:1,unitPrice:p.price,subtotal:p.price}]});setAddProductId('')}
 const confirm=async()=>{const result=await confirmOrder(editing.id,{notes:editing.notes||'',items});if(!result.ok){setModalError(result.error);return}setEditing(null);setMessage(`Pedido ${editing.publicCode} confirmado. Todavía no se generó la venta ni se modificó la caja.`)}
 const close=async order=>{if(!window.confirm(`¿Cerrar la venta de ${order.publicCode}? Esto descontará stock y registrará ${money(order.total)} en Caja como ${order.paymentMethod}.`))return;setClosingId(order.id);const result=await closeOrder(order.id,{notes:order.notes||''});setClosingId(null);if(!result.ok){setMessage(result.error);return}setMessage(`Venta ${result.sale.number} cerrada correctamente para ${order.publicCode}. Stock y Caja actualizados.`)}
 const cancel=async order=>{if(!window.confirm(`¿Cancelar ${order.publicCode}?`))return;try{await updateOrder(order.id,{status:'cancelled'});setMessage(`Pedido ${order.publicCode} cancelado.`)}catch(err){setMessage(err.message)}}
 const sendWhatsapp=order=>{const url=buildWhatsappUrl(order.phone,orderMessage(order));if(url)window.open(url,'_blank','noopener,noreferrer')}
 return <><div className="admin-page-header"><div><span className="section-kicker">Pedidos online</span><h1>Gestión de pedidos</h1><p>Confirmar valida el pedido y habilita el pago del cliente. Solo <strong>Cerrar venta</strong> descuenta stock, crea la venta y registra el ingreso en Caja.</p></div><button className="btn btn-secondary" onClick={()=>refreshOrders()}><RefreshCw size={17}/> Actualizar</button></div>{message&&<div className="notice-success">{message}</div>}
 <div className="order-admin-stats"><article><strong>{pending.length}</strong><span>Pendientes</span></article><article><strong>{confirmed.length}</strong><span>Esperando cobro</span></article><article><strong>{history.filter(x=>x.status==='closed').length}</strong><span>Ventas cerradas</span></article><article><strong>{history.filter(x=>x.status==='cancelled').length}</strong><span>Cancelados</span></article></div>
 <section><div className="panel-heading"><div><span className="section-kicker">Revisión</span><h2>Pedidos pendientes</h2></div></div><div className="orders-grid">{pending.length===0&&<div className="admin-panel empty-agenda full-span">No hay pedidos pendientes.</div>}{pending.map(order=><article className="admin-panel order-request" key={order.id}><div className="order-request-head"><div><span className="status pending">Pendiente</span><h2>{order.publicCode}</h2><p>{order.customerName} · {order.phone}</p></div></div><div className="order-mini-lines">{(order.items||[]).map(x=><span key={x.productId}>{x.quantity} × {x.name}</span>)}</div><div className="order-payment-line"><span>Pago elegido</span><strong>{order.paymentMethod||'—'}</strong></div><div className="order-request-total"><span>{dateTime(order.createdAt)}</span><strong>{money(order.total)}</strong></div><div className="request-actions"><button className="btn btn-primary" onClick={()=>open(order)}><Edit3 size={16}/> Revisar y confirmar</button><button className="btn btn-secondary" onClick={()=>cancel(order)}><XCircle size={16}/> Cancelar</button></div></article>)}</div></section>
 <section className="admin-panel confirmed-orders-panel"><div className="panel-heading"><div><span className="section-kicker">Pago pendiente de verificación</span><h2>Pedidos confirmados</h2><p>El cliente ya puede pagar. Cerrá la venta únicamente cuando el pago esté realizado/verificado.</p></div></div><div className="confirmed-order-list">{confirmed.length===0&&<div className="empty-agenda">No hay pedidos confirmados esperando cobro.</div>}{confirmed.map(order=><article className="confirmed-order-card" key={order.id}><div><span className="status confirmed">Confirmado</span><strong>{order.publicCode} · {order.customerName}</strong><small>{order.paymentMethod} · {money(order.total)}</small><small>Confirmado: {dateTime(order.confirmedAt||order.createdAt)}</small></div><div className="request-actions">{order.phone&&<button className="btn btn-secondary" onClick={()=>sendWhatsapp(order)}><MessageCircle size={15}/> WhatsApp</button>}<button className="btn btn-primary" disabled={closingId===order.id} onClick={()=>close(order)}><ShoppingBag size={16}/> {closingId===order.id?'Cerrando…':'Cerrar venta'}</button><button className="btn btn-secondary" onClick={()=>cancel(order)}><XCircle size={15}/> Cancelar</button></div></article>)}</div></section>
 {history.length>0&&<div className="admin-panel sales-history"><h2>Historial de pedidos</h2><div className="history-list">{history.slice(0,30).map(x=><article key={x.id}><div><strong>{x.publicCode}</strong><span>{x.customerName} · {x.paymentMethod||'—'} · {money(x.total)}</span><small>{dateTime(x.closedAt||x.createdAt)}</small></div><div className="request-actions"><span className={`status ${x.status}`}>{statusLabel(x.status)}</span></div></article>)}</div></div>}
 {editing&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><div className="modal modal-wide order-review-modal"><button className="modal-close" onClick={()=>setEditing(null)}>×</button><span className="section-kicker">Revisión de pedido</span><h2>{editing.publicCode}</h2><p className="modal-subtitle">{editing.customerName} · {editing.phone}. Confirmar todavía no genera una venta.</p><div className="order-payment-banner"><span>Medio de pago elegido por el cliente</span><strong>{editing.paymentMethod}</strong></div><div className="order-edit-lines">{items.map(row=>{const p=data.products.find(x=>x.id===row.productId);return <article key={row.productId}><div><strong>{row.name}</strong><small>Stock actual: {p?.stock??0}</small><input className="inline-price-input" type="number" min="0" value={row.unitPrice} onChange={e=>updatePrice(row.productId,e.target.value)}/></div><div className="qty-control"><button type="button" onClick={()=>updateQty(row.productId,row.quantity-1)}><Minus size={14}/></button><strong>{row.quantity}</strong><button type="button" onClick={()=>updateQty(row.productId,row.quantity+1)}><Plus size={14}/></button></div><strong>{money(row.quantity*row.unitPrice)}</strong><button type="button" className="danger-icon" onClick={()=>updateQty(row.productId,0)}><Trash2 size={15}/></button></article>})}</div><div className="order-add-product"><select value={addProductId} onChange={e=>setAddProductId(e.target.value)}><option value="">Agregar otro producto…</option>{data.products.filter(x=>x.active).map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name} · stock {p.stock}</option>)}</select><button type="button" className="btn btn-secondary" onClick={addProduct} disabled={!addProductId}><Plus size={16}/> Agregar</button></div>{modalError&&<div className="notice-error">{modalError}</div>}<div className="pos-total"><span>Total confirmado</span><strong>{money(total)}</strong></div><button className="btn btn-primary full-width" disabled={!items.length} onClick={confirm}><CheckCircle2 size={17}/> Confirmar pedido</button><small className="checkout-note">No descuenta stock ni registra Caja. Después de recibir/verificar el pago, usá “Cerrar venta”.</small></div></div>}
 </>
}
