import { useMemo,useState } from 'react'
import { Camera, PackagePlus, Plus, Trash2 } from 'lucide-react'
import { apiRepository } from '../../repositories/apiRepository'
import { useAppData } from '../../context/AppDataContext'
import { money,dateTime,calculateSuggestedPrice } from '../../utils/commerce'

export default function AdminPurchasesPage(){
 const {data,loading,registerPurchase}=useAppData(); const [supplierId,setSupplierId]=useState(''); const [invoice,setInvoice]=useState(''); const [paymentMethod,setPaymentMethod]=useState('Transferencia'); const [notes,setNotes]=useState(''); const [rows,setRows]=useState([{productId:'',quantity:1,unitCost:0}]); const [message,setMessage]=useState(''); const [scanBusy,setScanBusy]=useState(false); const [scanError,setScanError]=useState(''); const [ocrText,setOcrText]=useState('')
 const scanReceipt=async e=>{const file=e.target.files?.[0];if(!file)return;setScanBusy(true);setScanError('');try{const result=await apiRepository.analyzeReceipt(file);setOcrText(result.rawText||'');if(result.items?.length){setRows(result.items.map(x=>({productId:String(x.productId),quantity:x.quantity||1,unitCost:x.unitCost||0})));setMessage(result.message)}else setScanError(result.message||'No se detectaron productos vinculables.')}catch(err){setScanError(err.message)}finally{setScanBusy(false);e.target.value=''}}
 if(loading)return <div className="screen-loader">Cargando…</div>
 const suppliers=data.suppliers.filter(x=>x.active); const total=rows.reduce((s,r)=>s+(Number(r.quantity)||0)*(Number(r.unitCost)||0),0); const update=(i,p)=>setRows(v=>v.map((r,idx)=>idx===i?{...r,...p}:r)); const add=()=>setRows(v=>[...v,{productId:'',quantity:1,unitCost:0}]); const remove=i=>setRows(v=>v.length===1?v:v.filter((_,idx)=>idx!==i));
 const submit=async e=>{e.preventDefault(); const supplier=data.suppliers.find(x=>x.id===Number(supplierId)); const valid=rows.filter(r=>r.productId&&Number(r.quantity)>0); if(!supplier||!valid.length){setMessage('Seleccioná un proveedor y al menos un producto.');return} const result=await registerPurchase({supplierId:supplier.id,supplierName:supplier.name,invoiceNumber:invoice,paymentMethod,date:new Date().toISOString().slice(0,10),notes,items:valid.map(r=>({productId:Number(r.productId),quantity:Number(r.quantity),unitCost:Number(r.unitCost)}))}); setMessage(`Compra ${result.number} registrada. Stock y costos actualizados.`); setRows([{productId:'',quantity:1,unitCost:0}]);setInvoice('');setNotes('')}
 return <><div className="admin-page-header"><div><span className="section-kicker">Abastecimiento</span><h1>Compras y carga de stock</h1><p>Cada compra aumenta existencias, actualiza el último costo y puede recalcular el precio de venta.</p></div><label className="btn btn-secondary"><Camera size={17}/> {scanBusy?'Leyendo…':'Escanear comprobante'}<input hidden type="file" accept="image/*" capture="environment" onChange={scanReceipt}/></label></div>{message&&<div className="notice-success">{message}</div>}{scanError&&<div className="notice-error">{scanError}</div>}{ocrText&&<details className="admin-panel ocr-details"><summary>Ver texto detectado del comprobante</summary><pre>{ocrText}</pre></details>}
 <div className="purchase-layout"><form className="admin-panel purchase-form" onSubmit={submit}><div className="panel-title-row"><div><h2>Nueva compra</h2><p>Confirmar es una operación de inventario.</p></div><PackagePlus size={22}/></div><div className="form-grid"><label><span>Proveedor</span><select required value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Seleccionar…</option>{suppliers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label><span>Comprobante</span><input value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="FC-A 0001-000123"/></label></div><label><span>Medio de pago / cuenta</span><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}><option>Efectivo</option><option>Transferencia</option><option>Mercado Pago</option><option>Tarjeta / banco</option><option>Otro</option></select><small className="field-help">Al confirmar, el total se registra automáticamente como egreso en Caja.</small></label><div className="purchase-lines"><div className="purchase-line-head"><span>Producto</span><span>Cantidad</span><span>Costo unit.</span><span>Precio resultante</span><span></span></div>{rows.map((r,i)=>{const p=data.products.find(x=>x.id===Number(r.productId));const suggested=p?calculateSuggestedPrice(r.unitCost,p.pricingRules||[],data.settings?.priceRoundingStep||500,data.settings?.priceRoundingMode||'up'):0;return <div className="purchase-line" key={i}><select value={r.productId} onChange={e=>{const p2=data.products.find(x=>x.id===Number(e.target.value));update(i,{productId:e.target.value,unitCost:p2?.costPrice||0})}}><option value="">Producto…</option>{data.products.map(x=><option value={x.id} key={x.id}>{x.sku} · {x.name}</option>)}</select><input type="number" min="1" value={r.quantity} onChange={e=>update(i,{quantity:e.target.value})}/><input type="number" min="0" value={r.unitCost} onChange={e=>update(i,{unitCost:e.target.value})}/><strong>{p?.autoPrice?money(suggested):p?`${money(p.price)} manual`:'—'}</strong><button type="button" onClick={()=>remove(i)}><Trash2 size={16}/></button></div>})}</div><button type="button" className="inline-add" onClick={add}><Plus size={15}/> Agregar producto</button><label><span>Notas</span><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="purchase-total"><span>Costo total de compra</span><strong>{money(total)}</strong></div><button className="btn btn-primary full-width">Confirmar compra y actualizar stock</button></form>
 <aside className="admin-panel"><h2>Últimas compras</h2><div className="history-list">{(data.purchases||[]).slice(0,8).map(x=><article key={x.id}><div><strong>{x.number}</strong><span>{x.supplierName}</span><small>{dateTime(x.createdAt)} · {x.invoiceNumber||'Sin comprobante'}</small></div><strong>{money(x.totalCost)}</strong></article>)}</div></aside></div></>
}
